apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: concourse
  chart:
    repository: https://concourse-charts.storage.googleapis.com/
    name: concourse
    version: 11.2.2
  values:
    service:
      api:
        type: NodePort
        NodePort: 30001
      workerGateway:
        type: NodePort
        NodePort: 30002
    persistence:
      enabled: false
    postgresql:
      persistence:
        enabled: false
